import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./components/style.css"
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SafeSoft",
  description: "Generated by Nicka.cc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      
      <body className={inter.className}>
        <div className="bg-white text-black">
          <header><Header/></header>
        {children}
        <footer><Footer/></footer>
        </div>
        
      </body>
      
    </html>
  );
}
